# CMake generated Testfile for 
# Source directory: /dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry
# Build directory: /dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(geometry_dunefd "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_dunefd.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/test_geometry_dunefd.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./test_geometry_dunefd.fcl")
set_tests_properties(geometry_dunefd PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_dunefd.d")
add_test(geometry_dune35t "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_dune35t.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/test_geometry_dune35t.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./test_geometry_dune35t.fcl")
set_tests_properties(geometry_dune35t PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_dune35t.d")
add_test(geometry_dunedphase10kt "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_dunedphase10kt.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/test_geometry_dunedphase10kt.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./test_geometry_dunedphase10kt.fcl")
set_tests_properties(geometry_dunedphase10kt PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_dunedphase10kt.d")
add_test(geometry_dunedphase10kt_workspace "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_dunedphase10kt_workspace.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/test_geometry_dunedphase10kt_workspace.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./test_geometry_dunedphase10kt_workspace.fcl")
set_tests_properties(geometry_dunedphase10kt_workspace PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_dunedphase10kt_workspace.d")
add_test(geometry_iterator_loop_dunefd "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_iterator_loop_dunefd.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/test_geometry_iterator_loop_dunefd.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./test_geometry_iterator_loop_dunefd.fcl")
set_tests_properties(geometry_iterator_loop_dunefd PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_iterator_loop_dunefd.d")
add_test(geometry_crmchannelmapping_test "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_crmchannelmapping_test.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/test_geometry_dunedphase10kt.fcl" "--skip-return-code" "247" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/bin/geometry_crmchannelmapping_test" "--" "./test_geometry_dunedphase10kt.fcl")
set_tests_properties(geometry_crmchannelmapping_test PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/geometry_crmchannelmapping_test.d")
add_test(dump_channel_map_dune35t_test "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/dump_channel_map_dune35t_test.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/dump_dune35t_channelmap.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./dump_dune35t_channelmap.fcl")
set_tests_properties(dump_channel_map_dune35t_test PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/dump_channel_map_dune35t_test.d")
add_test(dump_channel_map_dunefd_test "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/dump_channel_map_dunefd_test.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/dump_dunefd_channelmap.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./dump_dunefd_channelmap.fcl")
set_tests_properties(dump_channel_map_dunefd_test PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/dump_channel_map_dunefd_test.d")
add_test(dump_channel_map_dunedphase10kt_test "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/dump_channel_map_dunedphase10kt_test.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/dump_dunedphase10kt_channelmap.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./dump_dunedphase10kt_channelmap.fcl")
set_tests_properties(dump_channel_map_dunedphase10kt_test PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/dump_channel_map_dunedphase10kt_test.d")
add_test(dump_channel_map_dunedphase10kt_workspace_test "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/dump_channel_map_dunedphase10kt_workspace_test.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/Geometry/dump_dunedphase10kt_workspace_channelmap.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./dump_dunedphase10kt_workspace_channelmap.fcl")
set_tests_properties(dump_channel_map_dunedphase10kt_workspace_test PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/Geometry/dump_channel_map_dunedphase10kt_workspace_test.d")
