
set( dunetpc_VERSION 06.43.00 )
set( dunetpc_UPS_VERSION v06_43_00 )


####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was product-config.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################


## find_ups_product directives
## remember that these are minimum required versions
    find_ups_product( larcoreobj  )
    find_ups_product( canvas  )
    find_ups_product( cppunit  )
    find_ups_product( clhep  )
    find_ups_product( cetlib_except  )
    find_ups_product( cetlib v2_01_00 )
    find_ups_boost( v1_50_0 )
    find_ups_product( sqlite  )
    find_ups_product( fhiclcpp  )
    find_ups_product( python  )
    find_ups_product( messagefacility  )
    find_ups_product( tbb  )
    find_ups_root(  )
    find_ups_product( larcore v1_00_00 )
    find_ups_product( larcorealg  )
    find_ups_product( art  )
    find_ups_product( larevt v1_00_00 )
    find_ups_product( lardataobj  )
    find_ups_product( nusimdata  )
    find_ups_product( lardata v1_00_00 )
    find_ups_product( nutools  )
    find_ups_product( genie  )
    find_ups_product( libwda  )
    find_ups_product( postgresql  )
    find_ups_product( geant4  )
    find_ups_product( xerces_c v3_0_0 )
    find_ups_product( range  )
    find_ups_product( larpandora v1_00_00 )
    find_ups_product( larsim v1_00_00 )
    find_ups_product( marley  )
    find_ups_product( ifdhc  )
    find_ups_product( larreco v1_00_00 )
    find_ups_product( pandora v02_00_00 )
    find_ups_product( larpandoracontent v02_04_00 )
    find_ups_product( eigen  )
    find_ups_product( larana v1_00_00 )
    find_ups_product( lbne_raw_data v0_00_02 )
    find_ups_product( artdaq_core v1_00_00 )
    find_ups_product( cetpkgsupport v1_08_03 )
    find_ups_product( TRACE v3_03_00 )
    find_ups_product( ifdh_art  )
    find_ups_product( ifbeam  )
    find_ups_product( nucondb  )


## find_library directives
    if( NOT XML2 )
      cet_find_library( XML2 NAMES xml2 PATHS /scratch/workspace/nu-release-build/v2_14_01/s50-e14/debug/build/libxml2/v2_9_4b/Linux64bit+2.6-2.12-debug/lib NO_DEFAULT_PATH )
    endif()
    if( NOT GREINSEGHAL )
      cet_find_library( GREINSEGHAL NAMES GReinSeghal PATHS ENV GENIE_LIB NO_DEFAULT_PATH )
    endif()
    if( NOT SIGC )
      cet_find_library( SIGC NAMES sigc-2.0 PATHS ENV LIBSIGCPP_LIB NO_DEFAULT_PATH )
    endif()
      set( DUNE_ARTSUPPORT  $ENV{DUNETPC_LIB}/libdune_ArtSupport.so )
      set( DUNE_DUNESERVICEACCESS  $ENV{DUNETPC_LIB}/libdune_DuneServiceAccess.so )
      set( DUNE_DUNECOMMON_SERVICE_GEOROPCHANNELGROUPSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DuneCommon_Service_GeoRopChannelGroupService_service.so )
      set( DUNE_DUNECOMMON_SERVICE_GEOAPACHANNELGROUPSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DuneCommon_Service_GeoApaChannelGroupService_service.so )
      set( DUNE_DUNECOMMON_SERVICE_DUNE35TCHANNELGROUPSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DuneCommon_Service_Dune35tChannelGroupService_service.so )
      set( DUNE_DUNECOMMON_SERVICE_FIXEDCHANNELGROUPSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DuneCommon_Service_FixedChannelGroupService_service.so )
      set( DUNE_DUNECOMMON  $ENV{DUNETPC_LIB}/libdune_DuneCommon.so )
      set( DUNE_GEOMETRY  $ENV{DUNETPC_LIB}/libdune_Geometry.so )
      set( DUNEGEOMETRYHELPER_SERVICE  $ENV{DUNETPC_LIB}/libDUNEGeometryHelper_service.so )
      set( CHECKGEOMETRY_MODULE  $ENV{DUNETPC_LIB}/libCheckGeometry_module.so )
      set( CHECKDPHASEGEOMETRY_MODULE  $ENV{DUNETPC_LIB}/libCheckDPhaseGeometry_module.so )
      set( SIGNALSHAPINGSERVICEDUNE_SERVICE  $ENV{DUNETPC_LIB}/libSignalShapingServiceDUNE_service.so )
      set( SIGNALSHAPINGSERVICEDUNE10KT_SERVICE  $ENV{DUNETPC_LIB}/libSignalShapingServiceDUNE10kt_service.so )
      set( SIGNALSHAPINGSERVICEDUNEDPHASE_SERVICE  $ENV{DUNETPC_LIB}/libSignalShapingServiceDUNEDPhase_service.so )
      set( DETPEDESTALSERVICEDUNE_SERVICE  $ENV{DUNETPC_LIB}/libDetPedestalServiceDUNE_service.so )
      set( SIGNALSHAPINGSERVICEDUNE34KT_SERVICE  $ENV{DUNETPC_LIB}/libSignalShapingServiceDUNE34kt_service.so )
      set( SIGNALSHAPINGSERVICEDUNE35T_SERVICE  $ENV{DUNETPC_LIB}/libSignalShapingServiceDUNE35t_service.so )
      set( FILECATALOGMETADATADUNE_SERVICE  $ENV{DUNETPC_LIB}/libFileCatalogMetadataDUNE_service.so )
      set( CHECKAUXDET_MODULE  $ENV{DUNETPC_LIB}/libCheckAuxDet_module.so )
      set( AVERAGEWAVEFORM_MODULE  $ENV{DUNETPC_LIB}/libAverageWaveform_module.so )
      set( CALIBRATIONANALYSIS_MODULE  $ENV{DUNETPC_LIB}/libCalibrationAnalysis_module.so )
      set( OPDETDIGIANADUNE_MODULE  $ENV{DUNETPC_LIB}/libOpDetDigiAnaDUNE_module.so )
      set( OPDETDIGITIZERDUNE_MODULE  $ENV{DUNETPC_LIB}/libOpDetDigitizerDUNE_module.so )
      set( DUNE35TONOPDETRESPONSE_SERVICE  $ENV{DUNETPC_LIB}/libDUNE35tonOpDetResponse_service.so )
      set( DUNEOPDETRESPONSE_SERVICE  $ENV{DUNETPC_LIB}/libDUNEOpDetResponse_service.so )
      set( SIMWIREDUNE10KT_MODULE  $ENV{DUNETPC_LIB}/libSimWireDUNE10kt_module.so )
      set( SIMWIREDUNE35T_MODULE  $ENV{DUNETPC_LIB}/libSimWireDUNE35t_module.so )
      set( DUNE_DETSIM  $ENV{DUNETPC_LIB}/libdune_DetSim.so )
      set( DUNE_DETSIM_TOOL_IDEALADCSIMULATOR_TOOL  $ENV{DUNETPC_LIB}/libdune_DetSim_Tool_IdealAdcSimulator_tool.so )
      set( DUNE_DETSIM_SERVICE_DUNE35TSIMCHANNELEXTRACTSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_Dune35tSimChannelExtractService_service.so )
      set( DUNE_DETSIM_SERVICE_GENERICSIMCHANNELEXTRACTSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_GenericSimChannelExtractService_service.so )
      set( DUNE_DETSIM_SERVICE_DPHASESIMCHANNELEXTRACTSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_DPhaseSimChannelExtractService_service.so )
      set( DUNE_DETSIM_SERVICE_EXPONENTIALCHANNELNOISESERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_ExponentialChannelNoiseService_service.so )
      set( DUNE_DETSIM_SERVICE_WHITECHANNELNOISESERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_WhiteChannelNoiseService_service.so )
      set( DUNE_DETSIM_SERVICE_PROVIDEDPEDESTALADDITIONSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_ProvidedPedestalAdditionService_service.so )
      set( DUNE_DETSIM_SERVICE_DUNE35TZEROSUPPRESSSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_Dune35tZeroSuppressService_service.so )
      set( DUNE_DETSIM_SERVICE_LEGACY35TZEROSUPPRESSSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_Legacy35tZeroSuppressService_service.so )
      set( DUNE_DETSIM_SERVICE_FIXEDZEROSUPPRESSSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_FixedZeroSuppressService_service.so )
      set( DUNE_DETSIM_SERVICE_REPLACECOMPRESSSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_ReplaceCompressService_service.so )
      set( DUNE_DETSIM_SERVICE_LARSOFTHUFFMANCOMPRESSSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_LarsoftHuffmanCompressService_service.so )
      set( DUNE_DETSIM_SERVICE_STUCKBITADCDISTORTIONSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_StuckBitAdcDistortionService_service.so )
      set( DUNE_DETSIM_SERVICE_FIXEDDETPEDESTALSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_FixedDetPedestalService_service.so )
      set( DUNE_DETSIM_SERVICE_DPHASEFIXEDDETPEDESTALSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DetSim_Service_DPhaseFixedDetPedestalService_service.so )
      set( SIMCOUNTER35T_MODULE  $ENV{DUNETPC_LIB}/libSimCounter35t_module.so )
      set( SIMWIREDUNE_MODULE  $ENV{DUNETPC_LIB}/libSimWireDUNE_module.so )
      set( DUNE_EVENTGENERATOR_PROTODUNEBEAM_MODULE  $ENV{DUNETPC_LIB}/libdune_EventGenerator_ProtoDUNEBeam_module.so )
      set( DUNE_DAQ_SERVICE_FILECHANNELMAPPINGSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_Daq_Service_FileChannelMappingService_service.so )
      set( DUNE_DAQ_SERVICE_DUNE35TCHANNELMAPPINGSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_Daq_Service_Dune35tChannelMappingService_service.so )
      set( CALGAUSHFDUNE10KT_MODULE  $ENV{DUNETPC_LIB}/libCalGausHFDUNE10kt_module.so )
      set( CALGAUSHFDUNE35T_MODULE  $ENV{DUNETPC_LIB}/libCalGausHFDUNE35t_module.so )
      set( CALWIREDUNE10KT_MODULE  $ENV{DUNETPC_LIB}/libCalWireDUNE10kt_module.so )
      set( CALWIREDUNE35T_MODULE  $ENV{DUNETPC_LIB}/libCalWireDUNE35t_module.so )
      set( CALWIREDUNEDPHASE_MODULE  $ENV{DUNETPC_LIB}/libCalWireDUNEDPhase_module.so )
      set( DECONVGAUSHFDUNE10KT_MODULE  $ENV{DUNETPC_LIB}/libDeconvGausHFDUNE10kt_module.so )
      set( DECONVGAUSHFDUNE35T_MODULE  $ENV{DUNETPC_LIB}/libDeconvGausHFDUNE35t_module.so )
      set( UNSTICKADCCODES_MODULE  $ENV{DUNETPC_LIB}/libUnstickADCCodes_module.so )
      set( DUNE_DATAPREP_TOOL_ADCDATADUMPER_TOOL  $ENV{DUNETPC_LIB}/libdune_DataPrep_Tool_AdcDataDumper_tool.so )
      set( DUNE_DATAPREP_SERVICE_CONFIGURABLEADCCHANNELDATACOPYSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_ConfigurableAdcChannelDataCopyService_service.so )
      set( DUNE_DATAPREP_SERVICE_INTERPOLATINGADCMITIGATIONSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_InterpolatingAdcMitigationService_service.so )
      set( DUNE_DATAPREP_SERVICE_STANDARDRAWDIGITEXTRACTSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_StandardRawDigitExtractService_service.so )
      set( DUNE_DATAPREP_SERVICE_THRESHOLDNOISEREMOVALSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_ThresholdNoiseRemovalService_service.so )
      set( DUNE_DATAPREP_SERVICE_MULTICHANNELNOISEREMOVALSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_MultiChannelNoiseRemovalService_service.so )
      set( DUNE_DATAPREP_SERVICE_DUNE35TNOISEREMOVALSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_Dune35tNoiseRemovalService_service.so )
      set( DUNE_DATAPREP_SERVICE_MEDIANPEDESTALSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_MedianPedestalService_service.so )
      set( DUNE_DATAPREP_SERVICE_ADCSUPPRESSSIGNALFINDINGSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_AdcSuppressSignalFindingService_service.so )
      set( DUNE_DATAPREP_SERVICE_DUNEDECONVOLUTIONSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_DuneDeconvolutionService_service.so )
      set( DUNE_DATAPREP_SERVICE_DUNEDPHASEDECONVOLUTIONSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_DuneDPhaseDeconvolutionService_service.so )
      set( DUNE_DATAPREP_SERVICE_KEEPALLROIBUILDINGSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_KeepAllRoiBuildingService_service.so )
      set( DUNE_DATAPREP_SERVICE_DUNEROIBUILDINGSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_DuneRoiBuildingService_service.so )
      set( DUNE_DATAPREP_SERVICE_DUNEDPHASEROIBUILDINGSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_DuneDPhaseRoiBuildingService_service.so )
      set( DUNE_DATAPREP_SERVICE_STANDARDADCWIREBUILDINGSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_StandardAdcWireBuildingService_service.so )
      set( DUNE_DATAPREP_SERVICE_STANDARDRAWDIGITPREPSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DataPrep_Service_StandardRawDigitPrepService_service.so )
      set( DATAPREPMODULE_MODULE  $ENV{DUNETPC_LIB}/libDataPrepModule_module.so )
      set( RAWEVD_MODULE  $ENV{DUNETPC_LIB}/libRawEVD_module.so )
      set( RAWEVD35T_MODULE  $ENV{DUNETPC_LIB}/libRawEVD35t_module.so )
      set( RAWEVDDP_MODULE  $ENV{DUNETPC_LIB}/libRawEVDDP_module.so )
      set( MUONOCCUPANCY_MODULE  $ENV{DUNETPC_LIB}/libMuonOccupancy_module.so )
      set( DUNEZSANALYSIS_MODULE  $ENV{DUNETPC_LIB}/libdunezsanalysis_module.so )
      set( DEDX_MODULE  $ENV{DUNETPC_LIB}/libdEdx_module.so )
      set( EMENERGYCALIB_MODULE  $ENV{DUNETPC_LIB}/libEMEnergyCalib_module.so )
      set( EMPI0ENERGY_MODULE  $ENV{DUNETPC_LIB}/libEMPi0Energy_module.so )
      set( DUNE_ANATREE_ANALYSISTREE_MODULE  $ENV{DUNETPC_LIB}/libdune_AnaTree_AnalysisTree_module.so )
      set( LBNE_DAQINPUT35T_UTILITIES  $ENV{DUNETPC_LIB}/liblbne_daqinput35t_utilities.so )
      set( LBNE_DAQINPUT35T  $ENV{DUNETPC_LIB}/liblbne_daqinput35t.so )
      set( DUNE_DAQINPUT35T_TPCMILLISLICEDUMP_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_TpcMilliSliceDump_module.so )
      set( DUNE_DAQINPUT35T_SSPDUMP_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_SSPDump_module.so )
      set( DUNE_DAQINPUT35T_SSPTOOFFLINE_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_SSPToOffline_module.so )
      set( DUNE_DAQINPUT35T_PTBTOOFFLINE_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_PTBToOffline_module.so )
      set( DUNE_DAQINPUT35T_SSPTRIGGERANA_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_SSPTriggerAna_module.so )
      set( DUNE_DAQINPUT35T_SSPDIAGNOSTICANA_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_SSPDiagnosticAna_module.so )
      set( DUNE_DAQINPUT35T_TPCDAQTOOFFLINE_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_TpcDAQToOffline_module.so )
      set( DUNE_DAQINPUT35T_NOISECORRELATION_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_NoiseCorrelation_module.so )
      set( DUNE_DAQINPUT35T_FILTERWF_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_FilterWF_module.so )
      set( DUNE_DAQINPUT35T_CHECKRAWDIGIT_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_CheckRawDigit_module.so )
      set( DUNE_DAQINPUT35T_SIGMOIDFILTER_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_Sigmoidfilter_module.so )
      set( DUNE_DAQINPUT35T_FILTERANALYZER_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_FilterAnalyzer_module.so )
      set( DUNE_DAQINPUT35T_FILTERANALYZERRUNLIST_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_FilterAnalyzerRunList_module.so )
      set( DUNE_DAQINPUT35T_GOODRUN_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_GoodRun_module.so )
      set( DUNE_DAQINPUT35T_BADTIMINGS_MODULE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_BadTimings_module.so )
      set( DUNE_DAQINPUT35T_SPLITTERINPUT_SOURCE  $ENV{DUNETPC_LIB}/libdune_daqinput35t_SplitterInput_source.so )
      set( RAWEVD35TTREE_MODULE  $ENV{DUNETPC_LIB}/libRawEVD35tTree_module.so )
      set( HITFINDERDUNE  $ENV{DUNETPC_LIB}/libHitFinderDUNE.so )
      set( EMLIKEHITS_MODULE  $ENV{DUNETPC_LIB}/libEmLikeHits_module.so )
      set( HITFINDER35T_MODULE  $ENV{DUNETPC_LIB}/libHitFinder35t_module.so )
      set( HITFINDERCOUNTER35T_MODULE  $ENV{DUNETPC_LIB}/libHitFinderCounter35t_module.so )
      set( HITFINDERPROTODUNESP_MODULE  $ENV{DUNETPC_LIB}/libHitFinderProtoDUNESP_module.so )
      set( HITHANDSCAN_MODULE  $ENV{DUNETPC_LIB}/libHitHandScan_module.so )
      set( HITREPEATER_MODULE  $ENV{DUNETPC_LIB}/libHitRepeater_module.so )
      set( ROBUSTHITFINDER_MODULE  $ENV{DUNETPC_LIB}/libRobustHitFinder_module.so )
      set( SHOWERHITSEPARATOR_MODULE  $ENV{DUNETPC_LIB}/libShowerHitSeparator_module.so )
      set( DISAMBIGCHECK_MODULE  $ENV{DUNETPC_LIB}/libdisambigcheck_module.so )
      set( TRACKANACT_MODULE  $ENV{DUNETPC_LIB}/libTrackAnaCT_module.so )
      set( DUNEPANDORA  $ENV{DUNETPC_LIB}/libDUNEPandora.so )
      set( DUNE35TPARTICLESTITCHER_MODULE  $ENV{DUNETPC_LIB}/libDUNE35tParticleStitcher_module.so )
      set( CTREE35T_MODULE  $ENV{DUNETPC_LIB}/libCTree35t_module.so )
      set( COUNTERFILTER_MODULE  $ENV{DUNETPC_LIB}/libCounterFilter_module.so )
      set( T0COUNTER_MODULE  $ENV{DUNETPC_LIB}/libT0Counter_module.so )
      set( GENEXTCOUNTERFILTER_MODULE  $ENV{DUNETPC_LIB}/libGenExtCounterFilter_module.so )
      set( LARG4EXTCOUNTERFILTER_MODULE  $ENV{DUNETPC_LIB}/libLArG4ExtCounterFilter_module.so )
      set( LARG4PARTICLEFILTER_MODULE  $ENV{DUNETPC_LIB}/libLArG4ParticleFilter_module.so )
      set( INISEGALG  $ENV{DUNETPC_LIB}/libIniSegAlg.so )
      set( MVAALG  $ENV{DUNETPC_LIB}/libMVAAlg.so )
      set( NUEANA_MODULE  $ENV{DUNETPC_LIB}/libNueAna_module.so )
      set( MVASELECT_MODULE  $ENV{DUNETPC_LIB}/libMVASelect_module.so )
      set( INISEGRECO_MODULE  $ENV{DUNETPC_LIB}/libIniSegReco_module.so )
      set( SHSEG_MODULE  $ENV{DUNETPC_LIB}/libShSeg_module.so )
      set( GAPFILTER_MODULE  $ENV{DUNETPC_LIB}/libGapFilter_module.so )
      set( GAPWIDTH_MODULE  $ENV{DUNETPC_LIB}/libGapWidth_module.so )
      set( PROTONIDENTIFICATION_MODULE  $ENV{DUNETPC_LIB}/libProtonIdentification_module.so )
      set( TRACKINGEFFICIENCY_MODULE  $ENV{DUNETPC_LIB}/libTrackingEfficiency_module.so )
      set( DUNE_SHOWERANA_SHOWERANALYSIS_MODULE  $ENV{DUNETPC_LIB}/libdune_ShowerAna_ShowerAnalysis_module.so )
      set( RUNHISTORYDUNE  $ENV{DUNETPC_LIB}/libRunHistoryDUNE.so )
      set( NEARLINEANA_MODULE  $ENV{DUNETPC_LIB}/libNearlineAna_module.so )
      set( MUONCOUNTER_MODULE  $ENV{DUNETPC_LIB}/libMuonCounter_module.so )
      set( MUONCOUNTERTIMES_MODULE  $ENV{DUNETPC_LIB}/libMuonCounterTimes_module.so )
      set( GOODWIREANA_MODULE  $ENV{DUNETPC_LIB}/libGoodWireAna_module.so )
      set( RECOTRACK_MODULE  $ENV{DUNETPC_LIB}/libRecoTrack_module.so )
      set( ROBUSTMCANA_MODULE  $ENV{DUNETPC_LIB}/libRobustMCAna_module.so )
      set( SIGNALTONOISE_MODULE  $ENV{DUNETPC_LIB}/libSignalToNoise_module.so )
      set( TIMEDIST_MODULE  $ENV{DUNETPC_LIB}/libTimeDist_module.so )
      set( CWPFILTER_MODULE  $ENV{DUNETPC_LIB}/libCWPFilter_module.so )
      set( DUNE_CLUSTERFINDERDUNE_CLUSTER3DDUNE35T_MODULE  $ENV{DUNETPC_LIB}/libdune_ClusterFinderDUNE_Cluster3DDUNE35t_module.so )
      set( DUNE_RECOALGDUNE_CLUSTER3DALGS  $ENV{DUNETPC_LIB}/libdune_RecoAlgDUNE_Cluster3DAlgs.so )
      set( ECALIBRATION_MODULE  $ENV{DUNETPC_LIB}/libECalibration_module.so )
      set( EDEPCAL_MODULE  $ENV{DUNETPC_LIB}/libEdepCal_module.so )
      set( HADCAL_MODULE  $ENV{DUNETPC_LIB}/libHadCal_module.so )
      set( RECOEFF_MODULE  $ENV{DUNETPC_LIB}/libRecoEff_module.so )
      set( RECOSTATS_MODULE  $ENV{DUNETPC_LIB}/libRecoStats_module.so )
      set( SPLIFETIME_MODULE  $ENV{DUNETPC_LIB}/libSPLifetime_module.so )
      set( CLUSTERCOUNTER_MODULE  $ENV{DUNETPC_LIB}/libClusterCounter_module.so )
      set( CLUSTERCOUNTER2_MODULE  $ENV{DUNETPC_LIB}/libClusterCounter2_module.so )
      set( CLUSTERCOUNTER3_MODULE  $ENV{DUNETPC_LIB}/libClusterCounter3_module.so )
      set( CLUSTERCOUNTER4_MODULE  $ENV{DUNETPC_LIB}/libClusterCounter4_module.so )
      set( CLUSTERCOUNTER5_MODULE  $ENV{DUNETPC_LIB}/libClusterCounter5_module.so )
      set( READBEAMINFO_MODULE  $ENV{DUNETPC_LIB}/libReadBeamInfo_module.so )
      set( DUNE_DAQTRIGGERSIM_TRIGGERDATAPRODUCTS  $ENV{DUNETPC_LIB}/libdune_DAQTriggerSim_TriggerDataProducts.so )
      set( DUNE_DAQTRIGGERSIM_TRIGGERDATAPRODUCTS_DICT  $ENV{DUNETPC_LIB}/libdune_DAQTriggerSim_TriggerDataProducts_dict.so )
      set( TRIGGERALGORITHMS  $ENV{DUNETPC_LIB}/libTriggerAlgorithms.so )
      set( ACTIVITYTRIGGERPROD_MODULE  $ENV{DUNETPC_LIB}/libActivityTriggerProd_module.so )
      set( TEMPLATETRIGGERPROD_MODULE  $ENV{DUNETPC_LIB}/libTemplateTriggerProd_module.so )
      set( TEMPLATETRIGGERANA_MODULE  $ENV{DUNETPC_LIB}/libTemplateTriggerAna_module.so )
      set( TESTHARDWAREMAPPER_MODULE  $ENV{DUNETPC_LIB}/libTestHardwareMapper_module.so )
      set( DUNE_DAQTRIGGERSIM_SERVICE_TEMPLATETRIGGERSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DAQTriggerSim_Service_TemplateTriggerService_service.so )
      set( DUNE_DAQTRIGGERSIM_SERVICE_HARDWAREMAPPERSERVICE_SERVICE  $ENV{DUNETPC_LIB}/libdune_DAQTriggerSim_Service_HardwareMapperService_service.so )
      set( DUNE_SPACECHARGE  $ENV{DUNETPC_LIB}/libdune_SpaceCharge.so )
      set( DUNE_SPACECHARGESERVICES_SPACECHARGESERVICEPROTODUNE_SERVICE  $ENV{DUNETPC_LIB}/libdune_SpaceChargeServices_SpaceChargeServiceProtoDUNE_service.so )
      set( DUNE_SPACECHARGESERVICES_SPACECHARGESERVICEDUNE35T_SERVICE  $ENV{DUNETPC_LIB}/libdune_SpaceChargeServices_SpaceChargeServiceDUNE35t_service.so )
      set( MAKESNETPROFILEHISTOS_MODULE  $ENV{DUNETPC_LIB}/libMakeSNeTProfileHistos_module.so )
      set( SUPERNOVAANA_MODULE  $ENV{DUNETPC_LIB}/libSupernovaAna_module.so )
      set( DUNE_DATAOVERLAYPRODUCTS  $ENV{DUNETPC_LIB}/libdune_DataOverlayProducts.so )
      set( DUNE_DATAOVERLAY_DATAOVERLAYPRODUCTS_DICT  $ENV{DUNETPC_LIB}/libdune_DataOverlay_DataOverlayProducts_dict.so )
      set( DUNE_RAWDIGITADDERANA  $ENV{DUNETPC_LIB}/libdune_RawDigitAdderAna.so )
      set( DUNE_RAWDIGITADDER  $ENV{DUNETPC_LIB}/libdune_RawDigitAdder.so )
      set( DUNE_RAWDIGITMIXER  $ENV{DUNETPC_LIB}/libdune_RawDigitMixer.so )
      set( DUNE_OPDETWAVEFORMMIXER  $ENV{DUNETPC_LIB}/libdune_OpDetWaveformMixer.so )
      set( DUNE_DATAOVERLAY_DATAOVERLAYMIXER_OVERLAYRAWDATADUNE35T_MODULE  $ENV{DUNETPC_LIB}/libdune_DataOverlay_DataOverlayMixer_OverlayRawDataDUNE35t_module.so )
      set( DUNE_DATAOVERLAY_DATAOVERLAYMIXER_RAWDIGITOVERLAYDUNE35TANA_MODULE  $ENV{DUNETPC_LIB}/libdune_DataOverlay_DataOverlayMixer_RawDigitOverlayDUNE35tAna_module.so )
      set( DAQSIMANA_MODULE  $ENV{DUNETPC_LIB}/libDAQSimAna_module.so )
      set( IMPORTFULL311FILE_SOURCE  $ENV{DUNETPC_LIB}/libImportFull311File_source.so )
      set( IMPORTSINGLE311EVENT_MODULE  $ENV{DUNETPC_LIB}/libImportSingle311Event_module.so )
      set( RAWDATA311INPUTDRIVER_SERVICE  $ENV{DUNETPC_LIB}/libRawData311InputDriver_service.so )
      set( DLARDAQ_SERVICE  $ENV{DUNETPC_LIB}/libdlardaq_service.so )
      set( EVENTDECODER_SERVICE  $ENV{DUNETPC_LIB}/libEventDecoder_service.so )
      set( HUFFDATACOMPRESSOR_SERVICE  $ENV{DUNETPC_LIB}/libHuffDataCompressor_service.so )
      set( TEST_DAQINPUT35T_SPLITTERANALYZER_MODULE  $ENV{DUNETPC_LIB}/libtest_daqinput35t_SplitterAnalyzer_module.so )
      set( GEOMETRYTEST35_MODULE  $ENV{DUNETPC_LIB}/libGeometryTest35_module.so )
      include_directories ( $ENV{DUNETPC_INC} )

check_required_components(dunetpc)

