# CMake generated Testfile for 
# Source directory: /dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/OpDet
# Build directory: /dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/OpDet
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(optical_sim_dune35t "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/OpDet/optical_sim_dune35t.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/OpDet/test_optical_sim_dune35t.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./test_optical_sim_dune35t.fcl")
set_tests_properties(optical_sim_dune35t PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/OpDet/optical_sim_dune35t.d")
add_test(optical_digi_dune35t "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/OpDet/optical_digi_dune35t.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/OpDet/test_optical_digi_dune35t.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./test_optical_digi_dune35t.fcl")
set_tests_properties(optical_digi_dune35t PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/OpDet/optical_digi_dune35t.d")
add_test(optical_reco_dune35t "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/OpDet/optical_reco_dune35t.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/OpDet/test_optical_reco_dune35t.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./test_optical_reco_dune35t.fcl")
set_tests_properties(optical_reco_dune35t PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/OpDet/optical_reco_dune35t.d")
add_test(build_oplib_dune35t "/cvmfs/fermilab.opensciencegrid.org/products/larsoft/cetbuildtools/v5_09_01/bin/cet_exec_test" "--wd" "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/OpDet/build_oplib_dune35t.d" "--required-files" "" "--datafiles" "/dune/app/users/soughton/larsoft_v06_43_00/srcs/dunetpc/test/OpDet/test_build_oplib_dune35t.fcl" "--skip-return-code" "247" "lar" "--rethrow-all" "--config" "./test_build_oplib_dune35t.fcl")
set_tests_properties(build_oplib_dune35t PROPERTIES  SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/dune/app/users/soughton/larsoft_v06_43_00/build_slf6.x86_64/dunetpc/test/OpDet/build_oplib_dune35t.d")
